In [1]:
# Import the random module.
import random

In [2]:
random.randint(-90,90)

30

In [4]:
random.random()

0.9574555572090956

In [5]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1

In [7]:
random.uniform(-90, 90)

-63.751514630435985

In [9]:
# Import the NumPy module.
import numpy as np

In [11]:
np.random.uniform(-90.000, 90.000, size=50)

array([-35.00788229, -76.84891054,  -2.34856935,  -6.27057589,
        13.31859025, -65.21950153, -64.83441921, -87.96846178,
       -89.41274561, -20.14979236,  79.19669416, -76.37868307,
        -3.04125119,  80.08474366, -16.72597962,  -2.86923418,
        57.43401469, -14.74578372,  51.70881927,  76.60663123,
       -58.14564879,  32.52944486,  74.54871576, -69.19174361,
       -39.223208  ,  -4.09690885,   8.94519314, -50.64722062,
       -18.33362335, -83.75758755,  -8.00032702,   5.51350509,
       -45.00922124,  39.46100365, -64.6440898 , -71.71119247,
       -51.29516289, -61.28440982,  10.59589897,  19.96616306,
       -54.4233436 , -14.78868749, -85.0176464 ,  22.16902653,
       -69.31239205,  88.67513305, -14.59500848,  -2.38838888,
       -64.10360057, -51.40345625])

In [12]:
# Import timeit.
import timeit

In [19]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 40.22266693, -45.18940011,  66.57969878, ...,  47.22241663,
       -29.79544798,  64.59094272])

In [17]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

836 µs ± 8.32 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [20]:
np.random.uniform(-180.000, 180.000, size=1500)

array([ -79.66845164, -130.92160143,  154.67470823, ...,   55.47071233,
       -171.83848321,   70.68952905])